version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: DockerFile_app
    container_name: backoffice
    restart: always
    image: backoffice_image
    ports:
      - 8080:8080